Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude: 
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'
    - 'config/environments/development'

Metrics/BlockLength:
  Max: 30
