Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude: 
    - 'bin/bundle'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 15
